### ISSUE TITLE
Use LipidLynxX in Python directly?

### ISSUE THREAD

**Issue by meowcat** [SysMedOs/LipidLynxX#18]
**Is your feature request related to a problem? Please describe.**

Right now LipidLynxX can be used from the Web GUI and with a Web API.
Is there any way to use the conversion in Python directly? Probably it works already but is not documented...

**Describe the solution you'd like**
In practice, I would be looking to do something like

```python
import lipidlynx.parser as lp

lp.parse_lipid("SM 21:0;2O/21:1") 
```

and get back some kind of pandas dataframe or similar with the lipid level matrix.

**Describe alternatives you've considered**
The GOSLIN packages do something similar, but don't currently cover all features the latest LIPIDMAPS nomenclature.

**Comment by meowcat** [comment]
Sorry, consider me stupid, the notebooks have it all.

**Comment by ZhixuNi** [comment]
Hi @meowcat !

Many thanks for the feadback!
The notebook might be a bit out of date code, since it might not be updated (my mistake :crying_cat_face: )

But you can check the file `lynx/tools.py`

All CLI commands are basically running through that.
There is a on going dev method parse to parse the lipid names into json object.
However, it is still under development...
you can find some code here:
`lynx/controllers/parser.py`
and
`lynx/controllers/decoder.py`

We are still working on it to bring more features.

Hope this can help you to develop your project!

**Comment by meowcat** [comment]
I have added a `setup.py` and `MANIFEST.in` so one can install this as a module with `python setup.py install` (note: the requirements need to be done with `pip -r requirements.txt` before) in the branch https://github.com/meowcat/LipidLynxX/tree/install-package. Feel free to pull this (or suggest a better way to do this, I'm not exactly well-versed at packaging Python stuff)
